name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Changed from read to write for PR creation
      pull-requests: write  # Changed from read to write for PR creation
      issues: write  # Changed from read to write for commenting on issues
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # This setting allows Claude to read CI results and create/edit PRs
          additional_permissions: |
            actions: read
            contents: write
            pull-requests: write
            issues: write
          
          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          model: "claude-opus-4-20250514"
          
          # Optional: Customize the trigger phrase (default: @claude)
          # trigger_phrase: "/claude"
          
          # Optional: Trigger when specific user is assigned to an issue
          # assignee_trigger: "claude-bot"
          
          # Allow Claude to run git commands for PR creation and npm commands
          allowed_tools: "Bash(npm install),Bash(npm run build),Bash(npm run test:*),Bash(npm run lint:*),Bash(git:*),Bash(gh:*)"
          
          # Custom instructions for Claude to handle PR creation from issues
          custom_instructions: |
            When asked to create a PR from an issue comment:
            1. Create a new branch for the changes
            2. Make the requested changes
            3. Create a pull request with a clear description
            4. Link the PR to the original issue
            Follow TypeScript conventions and ensure code quality
          
          # Optional: Custom environment variables for Claude
          # claude_env: |
          #   NODE_ENV: test

